### ISSUE TITLE
Juju install instructions are wrong

### ISSUE THREAD

**Issue by popey** [canonical/landscape-docs#113]
https://docs.ubuntu.com/landscape/en/onprem leads to https://docs.ubuntu.com/landscape/en/landscape-install-juju which says `sudo apt-get install juju`. On an 18.04 container, I get this:

```
ubuntu@landscape-juju:~$ sudo apt-get install juju
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "juju", but there is a snap with that name.
Try "snap install juju"

E: Unable to locate package juju
```

We should probably not give people a bum-steer on the first line of the docs.

**Comment by Roadmaster** [comment]
I would change to "follow the instructions in https://jaas.ai/docs/installing"; we could change our one-line instructions to "sudo snap install juju" as well to avoid sending people on a wild goose chase.

CONFIRMED>
