### ISSUE TITLE
Where the heck do we get help with our SaaS account?

### ISSUE THREAD

**Issue by dsghi** [canonical/landscape-docs#128]
On the bottom of the landscape.canonical.com site, there is a link to help: https://help.landscape.canonical.com, which redirects to https://docs.ubuntu.com/landscape/en/. However, nowhere on this site is there any information on how to reach technical support for Landscape. This is really something that should be in the FAQs...

**Comment by anthonydillon** [comment]
Hi @dsghi 

Please can you open a case with us at https://support.canonical.com? We can then work with you to get this resolved.

I will leave this issue open to resolve the missing content link.
